export default {

  ROUND_LOAD_ROUNDS: 'ROUND_LOAD_ROUNDS',
  ROUND_SET_ACTIVE: 'ROUND_SET_ACTIVE',
  TIMER_INIT: 'TIMER_INIT',
  TIMER_START: 'TIMER_START',
  TIMER_PAUSE: 'TIMER_PAUSE',
  TIMER_RESET: 'TIMER_RESET',
  TIMER_TICK: 'TIMER_TICK'

}
